use-grammars = { only = [
  "bash",
  "c",
  "c-sharp",
  "clojure",
  "common-lisp",
  "cpp",
  "crystal",
  "css",
  "d",
  "dart",
  "eex",
  "ejs",
  "env",
  "erb",
  "erlang",
  "fsharp",
  "git-attributes",
  "git-commit",
  "git-config",
  "git-ignore",
  "git-rebase",
  "gleam",
  "go",
  "gomod",
  "gotmpl",
  "gowork",
  "heex",
  "html",
  "ini",
  "janet",
  "java",
  "javascript",
  "jinja",
  "json",
  "jsonc",
  "jsx",
  "just",
  "log",
  "lua",
  "make",
  "markdown",
  "nim",
  "nix",
  "ocaml",
  "ocaml-interface",
  "protobuf",
  "python",
  "racket",
  "ruby",
  "rust",
  "scheme",
  "sql",
  "toml",
  "tsx",
  "typescript",
  "yaml"
]}
